name       : perl-test-leaktrace
version    : '0.17'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/L/LE/LEEJO/Test-LeakTrace-0.17.tar.gz : 777d64d2938f5ea586300eef97ef03eacb43d4c1853c9c3b1091eb3311467970
homepage   : https://metacpan.org/pod/Test::LeakTrace
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::LeakTrace - Traces memory leaks
description: |
    Test::LeakTrace provides several functions that trace memory leaks. This module scans arenas, the memory allocation system, so it can detect any leaked SVs in given blocks.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
