name       : perl-test-leaktrace
version    : 0.16
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/L/LE/LEEJO/Test-LeakTrace-0.16.tar.gz : 5f089eed915f1ec8c743f6d2777c3ecd0ca01df2f7b9e10038d316952583e403
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::LeakTrace - Traces memory leaks
description: |
    Test::LeakTrace - Traces memory leaks
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
